@startuml
state "Reading" as RD
state "Reading & Pause" as RP
state "Writing" as WR
[*] --> RD
RD --> RD : Recv Rx chars\n/Restart timer
RD --> RD : Recv Tx message/\nPut into Tx-RB
RD --> RP : timer timeout\n[TxRB empty]
RP --> RD : Recv Rx chars
RD --> WR : timer timeout\n[TxRB !empty]
RP --> WR : Recv Tx message/\nPut into Tx-RB
state RD : Entry/\n\tStart timer
state WR : Entry/\n\tunlock rbblock mutex
WR --> RD : Tx-th notify of TxRB empty
@enduml