@startuml
start
repeat
    :Prohibit Tx;
    :Start 1-shot delay;
    :blocking read();
    :Put bytes into rxrb;
    if (rxrb overflows?) then (yes)
        :goto error processing;
    endif
    if (event is available) then (yes)
        :send the event to PHY FSM;
    endif
repeat while (forever)
end
@enduml